services:
  mongo:
    image: 'mongo'
    container_name: tf-studies-mongodb
    ports:
      - '4567:27017'
  api:
    restart: unless-stopped
    build: ./apps/server
    ports:
      - 3000:3000
    environment:
      MONGO_DB: mongodb://mongo/tf-studies
  web:
    restart: unless-stopped
    build: ./apps/web
    ports:
      - 4000:4000
